language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-plump' ]; then cd .. && eval "mv $currentfolder generator-plump" && cd generator-plump; fi

